# Generated by Django 3.0.5 on 2020-04-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200419_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('album', 'album')], default='album', max_length=64),
        ),
    ]
