# Generated by Django 3.0.5 on 2020-05-31 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order_form', '0007_orders_is_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmations_link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=32, unique=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order_form.Orders')),
            ],
        ),
    ]
