# Generated by Django 3.0.5 on 2020-04-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='duration',
        ),
        migrations.AlterField(
            model_name='song',
            name='songfile',
            field=models.FileField(upload_to='audio'),
        ),
    ]
