# Generated by Django 3.0.5 on 2020-04-12 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
        ('song', '0002_auto_20200412_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='id_in_track',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.Track'),
        ),
        migrations.AlterField(
            model_name='song',
            name='songfile',
            field=models.FileField(blank=True, null=True, upload_to='audio'),
        ),
    ]
