# Generated by Django 3.0.5 on 2020-04-12 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_track_description'),
        ('song', '0004_auto_20200412_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.Track'),
        ),
    ]
