# Generated by Django 3.0.5 on 2020-04-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0006_song_friendly_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='song',
            name='friendly_link',
            field=models.SlugField(blank=True, max_length=60),
        ),
    ]
