# Generated by Django 3.0.5 on 2020-04-12 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExternalLinks',
            new_name='ExternalLink',
        ),
    ]
