# Generated by Django 3.0.5 on 2020-04-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_form', '0002_auto_20200419_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='adress',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='city_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='house_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='zip_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
