# Generated by Django 3.0.5 on 2020-04-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_form', '0003_auto_20200419_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='user_agreement',
            field=models.BooleanField(default=False),
        ),
    ]
