# Generated by Django 3.0.5 on 2020-05-31 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_form', '0006_auto_20200426_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
