# Generated by Django 3.0.5 on 2020-04-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
