# Generated by Django 3.0.5 on 2020-04-12 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_track_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='friendly_link',
            field=models.SlugField(blank=True, max_length=60, unique=True),
        ),
    ]
